services:
  app-stage:
    image: app-stage
    container_name: app-stage
    build:
      context: .
      dockerfile: Dockerfile.stage
      network: host
      secrets:
        - ENV_WITH_SECRETS
    ports:
      - 3000:3000
    volumes:
      - ./uploads:/app/uploads
    env_file:
      - ./envs/staging/.env.staging.docker.local
    networks:
      - internal-stage
    depends_on:
      - db-stage

  db-stage:
    image: postgres:16.2-alpine
    container_name: db-stage
    ports:
      - 5432:5432
    user: '${MY_UID}:${MY_GID}'
    volumes:
      - db-stage-data:/var/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data/data-stage
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
    secrets:
      - postgres_user
      - postgres_password
      - postgres_db
    networks:
      - internal-stage

volumes:
  db-stage-data:

networks:
  internal-stage:
    external: false

secrets:
  ENV_WITH_SECRETS:
    file: .env.staging.local
  postgres_user:
    file: secrets/staging/postgres-user.txt
  postgres_password:
    file: secrets/staging/postgres-password.txt
  postgres_db:
    file: secrets/staging/postgres-db.txt
