services:
  app-dev:
    image: app-dev
    container_name: app-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - app-dev-node_modules:/app/node_modules
      - app-dev-next:/app/.next
      - ./uploads:/app/uploads
    env_file:
      - ./envs/development/.env.development.docker
      - ./envs/development/.env.development.docker.local
    networks:
      - internal-dev
    depends_on:
      - db-dev

  db-dev:
    image: postgres:16.2-alpine
    container_name: db-dev
    ports:
      - 5432:5432
    user: '${MY_UID}:${MY_GID}'
    volumes:
      - db-dev-data:/var/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data/data-dev
    env_file:
      - ./envs/development/.env.development.docker.local
    networks:
      - internal-dev

volumes:
  app-dev-node_modules:
  app-dev-next:
  db-dev-data:

networks:
  internal-dev:
    external: false
