services:
  app-stage:
    image: app-stage
    container_name: app-stage
    build:
      context: .
      dockerfile: Dockerfile.prod
      network: host
      secrets:
        - ENV_WITH_SECRETS
    ports:
      - 3000:3000
    volumes:
      - ./uploads:/app/uploads
    env_file:
      - ./envs/staging/.env.staging.docker
      - ./envs/staging/.env.staging.docker.local
    networks:
      - internal-stage
    depends_on:
      - db-stage
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 80s

  db-stage:
    image: postgres:16.2-alpine
    container_name: db-stage
    ports:
      - 5432:5432
    user: '${MY_UID}:${MY_GID}'
    volumes:
      - db-stage-data:/var/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data/data-stage
    env_file:
      - ./envs/staging/.env.staging.docker.local
    networks:
      - internal-stage
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  app-stage-node_modules:
  app-stage-next:
  db-stage-data:

networks:
  internal-stage:
    external: false

secrets:
  ENV_WITH_SECRETS:
    file: .env.staging.local
